#!/usr/bin/env python3
"""Template: SCENE_GEN — write a valid scene_state.json fixture.

Modify ONLY the PARAMS block. This template:
1. Writes a minimal valid scene_state.json with rooms, walls, furniture, TX/RX
2. Runs a self-test for in-bounds + AABB-collision
3. Saves placeholder simulation_result.json (in case downstream tasks read it)

Schema: see references/scene-state-schema.md.
"""
from __future__ import annotations

# ============================================================================
# PARAMETER BLOCK — MODIFY ONLY THIS SECTION
# ============================================================================
PARAMS = {
    "name": "Generated Room",
    "description": "Generated by template_scene.py",
    "bounds": {"width": 10.0, "depth": 8.0, "height": 3.0},
    "frequency_hz": 3.5e9,
    "room_type": "office",
    "wall_material": "itu_concrete",
    "floor_material": "itu_concrete",
    "ceiling_material": "itu_plasterboard",
    # furniture: list of {type, x, y, theta_deg, w, h, material}
    "furniture": [
        {"type": "desk", "x": 2.0, "y": 2.0, "theta_deg": 0,
         "w": 1.4, "h": 0.7, "material": "itu_wood"},
        {"type": "chair", "x": 2.0, "y": 3.2, "theta_deg": 0,
         "w": 0.5, "h": 0.5, "material": "itu_wood"},
    ],
    # transmitters: list of {id, x, y, z, power_dbm}
    "transmitters": [
        {"id": "tx_1", "x": 5.0, "y": 4.0, "z": 2.8, "power_dbm": 20.0},
    ],
    # receivers: optional grid
    "receivers": [
        {"id": "rx_grid", "type": "grid", "height": 1.5, "resolution": 0.5},
    ],
    "output_dir": ".",
}
# ============================================================================

import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def aabb_overlap(a, b):
    """Axis-aligned bounding-box collision test."""
    return not (a["x"] + a["w"]/2 <= b["x"] - b["w"]/2 or
                b["x"] + b["w"]/2 <= a["x"] - a["w"]/2 or
                a["y"] + a["h"]/2 <= b["y"] - b["h"]/2 or
                b["y"] + b["h"]/2 <= a["y"] - a["h"]/2)


def validate(p):
    errors = []
    b = p["bounds"]
    if not (b["width"] > 0 and b["depth"] > 0 and b["height"] > 0):
        errors.append("bounds must be positive")
    # Furniture in bounds
    for i, f in enumerate(p["furniture"]):
        if not (0 <= f["x"] <= b["width"] and 0 <= f["y"] <= b["depth"]):
            errors.append(f"furniture[{i}] outside bounds: {f}")
    # TX in bounds
    for i, t in enumerate(p["transmitters"]):
        if not (0 <= t["x"] <= b["width"] and 0 <= t["y"] <= b["depth"]
                and 0 < t["z"] <= b["height"]):
            errors.append(f"transmitter[{i}] outside bounds: {t}")
    # AABB pairwise furniture
    for i in range(len(p["furniture"])):
        for j in range(i+1, len(p["furniture"])):
            if aabb_overlap(p["furniture"][i], p["furniture"][j]):
                errors.append(f"furniture[{i}] overlaps furniture[{j}]")
    return errors


def build_scene_state(p: dict) -> dict:
    now = datetime.now(timezone.utc).isoformat()
    rid = f"room_{p['room_type']}_main"
    b = p["bounds"]
    walls = [
        {"id": f"wall_{i}", "room_id": rid,
         "start": list(s), "end": list(e),
         "thickness": 0.15, "material": p["wall_material"],
         "has_window": False, "has_door": False}
        for i, (s, e) in enumerate([
            ([0, 0], [b["width"], 0]),
            ([b["width"], 0], [b["width"], b["depth"]]),
            ([b["width"], b["depth"]], [0, b["depth"]]),
            ([0, b["depth"]], [0, 0]),
        ])
    ]
    furniture = [
        {"id": f"furn_{f['type']}_{i:02d}", "type": f["type"],
         "catalog_id": None,
         "position": [f["x"], f["y"], 0.0],
         "orientation_deg": f.get("theta_deg", 0),
         "dimensions": [f["w"], f["h"], 0.75],
         "material": f.get("material", "itu_wood"),
         "visible": True}
        for i, f in enumerate(p["furniture"])
    ]
    transmitters = [
        {"id": t["id"], "name": t["id"], "position": [t["x"], t["y"], t["z"]],
         "power_dbm": t["power_dbm"], "frequency_hz": p["frequency_hz"],
         "antenna": {"type": "isotropic", "pattern": None,
                     "polarization": "V", "mimo_config": None},
         "orientation_deg": 0, "visible": True}
        for t in p["transmitters"]
    ]
    receivers = [
        {"id": r["id"], "type": r.get("type", "grid"),
         "height": r.get("height", 1.5),
         "resolution": r.get("resolution", 0.5),
         "bounds": [[0, 0], [b["width"], b["depth"]]], "visible": True}
        for r in p.get("receivers", [])
    ]
    return {
        "version": "2.0",
        "meta": {"created": now, "modified": now,
                 "name": p["name"], "description": p["description"]},
        "scene": {"type": "indoor", "origin": "SW",
                  "coordinate_system": {"x": "east", "y": "north", "z": "up",
                                        "theta_zero": "north", "units": "meters"},
                  "bounds": b, "frequency_hz": p["frequency_hz"],
                  "source_format": "template_scene"},
        "rooms": [{
            "id": rid, "name": p["name"], "type": p["room_type"],
            "polygon": [[0, 0], [b["width"], 0],
                        [b["width"], b["depth"]], [0, b["depth"]]],
            "height": b["height"],
            "materials": {"walls": p["wall_material"],
                          "floor": p["floor_material"],
                          "ceiling": p["ceiling_material"]}
        }],
        "walls": walls,
        "furniture": furniture,
        "transmitters": transmitters,
        "receivers": receivers,
        "constraints": [],
        "simulation_results": [],
        "export_history": [],
        "code_artifacts": [],
    }


def main():
    errors = validate(PARAMS)
    if errors:
        sys.stderr.write("\nSELF_TEST FAIL: " + "; ".join(errors) + "\n")
        sys.exit(2)

    out = Path(PARAMS["output_dir"])
    out.mkdir(parents=True, exist_ok=True)

    scene = build_scene_state(PARAMS)
    (out / "scene_state.json").write_text(json.dumps(scene, indent=2))

    # Placeholder simulation_result.json (skill rule #6)
    placeholder = {
        "schema_version": "1.0", "task_type": "scene_gen",
        "status": "success", "method": "template_scene",
        "numerical_metrics": {
            "num_rooms": 1, "num_walls": len(scene["walls"]),
            "num_furniture": len(scene["furniture"]),
            "num_transmitters": len(scene["transmitters"]),
            "scene_area_m2": round(
                PARAMS["bounds"]["width"] * PARAMS["bounds"]["depth"], 2),
        },
        "warnings": [],
    }
    (out / "simulation_result.json").write_text(json.dumps(placeholder, indent=2))

    print(f"Scene written: {len(scene['furniture'])} furniture, "
          f"{len(scene['transmitters'])} TX, "
          f"area={placeholder['numerical_metrics']['scene_area_m2']} m²")


if __name__ == "__main__":
    import os
    if not os.environ.get("RF_SKIP_TEMPLATE_WARN"):
        sys.stderr.write(
            "\n*** TEMPLATE WARNING ***\n"
            "This is a TEMPLATE — copy the file to your workdir and edit\n"
            "PARAMS before running. Default PARAMS will run, but they're\n"
            "for reference only and may not match your task. Set\n"
            "RF_SKIP_TEMPLATE_WARN=1 to silence.\n"
            "\n"
        )
    main()
